asm первая попытка сдачи
sancho20021/first-term pull request #1
Opened 2020-06-28 19:22 UTC by sancho20021

Я написал ассемблер, тесты работают, проверил. Честно.

2020-06-29 00:00 UTC, kt-cpp commented on asm/mul.asm
> +                call            read_long
Я конечно понимаю зачем ты написал с таким смещением, но на асме так не пишут

Выдели в блоки просто

2020-06-29 00:01 UTC, kt-cpp commented on asm/mul.asm
> +		ret
Слишком много копипасты

Не говоря о том, что ```src``` не указан в названиях функций

2020-06-29 00:04 UTC, kt-cpp requested changes
Поменяй ```qword_kol``` на 128, убедись что тесты не проходят, исправь

(Ты считываешь 256 разрядные длинные числа, корректный ответ не всегда 256 разрядный, ты это не учитываешь)
где разряд это 64 бита

2020-07-01 21:22 UTC, sancho20021 commented on asm/mul.asm
> +                call            read_long
Я честно пытался исправить но все стало еще хуже. в IDE все очень ровно выглядит.

2020-07-01 21:23 UTC, sancho20021 commented on asm/mul.asm
> +		ret
Как я вообще додумался сделать 5 методов копирования я не помню, но теперь всего 1)

2020-07-01 21:24 UTC, sancho20021 commented
Я немного переделал код mul, теперь он намного проще и лучше

2020-07-01 21:49 UTC, kt-cpp commented on asm/mul.asm
> +        clc
не нужно

2020-07-01 21:49 UTC, kt-cpp commented on asm/mul.asm
> +        push        r15 ;counter
Пустую строку после этой строчки

2020-07-01 21:50 UTC, kt-cpp commented on asm/mul.asm
> +        lea             r10, [rsp+2*num_len];r10 will be the address for temporary calculations (from 3th to 4th blocks
Давай выделим место под temporary calculations в функции mul_long_long

2020-07-01 21:50 UTC, kt-cpp commented on asm/mul.asm
> +        mov             rcx, qword_kol
Эта строка не нужна

2020-07-01 21:52 UTC, kt-cpp commented on asm/mul.asm
> +        call        mul_long_short
Для вызова этой функции достаточно rcx = qword_kol + 1 (собственно и памяти достаточно, так что давай не выделять лишние байтики)

Кстати переименуй qword_kol -> qword_amount хотя бы ...

2020-07-01 21:53 UTC, kt-cpp commented on asm/mul.asm
> +        lea         r14, [r10+r11]    ;shift b
Кстати косвенная адресация работает медленее, чем если бы ты `r10` двигал постоянно

Но я в этом не уверен, можно погуглить ...

2020-07-01 21:54 UTC, kt-cpp requested changes
Уже лучше

2020-07-01 23:33 UTC, sancho20021 commented on asm/mul.asm
> +        clc
Ок

2020-07-01 23:33 UTC, sancho20021 commented on asm/mul.asm
> +        push        r15 ;counter
Ок

2020-07-01 23:33 UTC, sancho20021 commented on asm/mul.asm
> +        lea             r10, [rsp+2*num_len];r10 will be the address for temporary calculations (from 3th to 4th blocks
Сделал

2020-07-01 23:34 UTC, sancho20021 commented on asm/mul.asm
> +        mov             rcx, qword_kol
Ну, я убрал вообще использование qword_kol из multiply_long_long

2020-07-01 23:34 UTC, sancho20021 commented on asm/mul.asm
> +        call        mul_long_short
Готово

2020-07-01 23:35 UTC, sancho20021 commented on asm/mul.asm
> +        lea         r14, [r10+r11]    ;shift b
Я тоже не знаю, может и так сойдет?)

2020-07-02 15:17 UTC, kt-cpp commented on asm/mul.asm
> +        lea         r14, [r10+r11]    ;shift b
Сойдет

2020-07-02 15:19 UTC, kt-cpp commented on asm/mul.asm
> +        shl     rcx, 3
Тут должна быть 4?

2020-07-02 15:20 UTC, kt-cpp commented on asm/mul.asm
> +        shr         rcx, 4
Что за бред? Сделай нормально.

2020-07-02 15:20 UTC, kt-cpp commented on asm/mul.asm
> +        shl     rcx, 3
А, нет. Все равно не очень

2020-07-02 15:21 UTC, kt-cpp commented on asm/mul.asm
> +        shr         rcx, 4
И выдели 128 * 8 + 8, ведь необходимости в 256 * 8 уже нет

2020-07-02 15:21 UTC, kt-cpp requested changes
Какой-то странный код появился

Давай еще одну оптимизацию на память и закончим

2020-07-02 18:24 UTC, sancho20021 commented on asm/mul.asm
> +        shl     rcx, 3
Да, теперь по-другому

2020-07-02 18:25 UTC, sancho20021 commented on asm/mul.asm
> +        shr         rcx, 4
Понял. ХитрО

2020-07-02 19:31 UTC, kt-cpp requested changes
Ок

2020-07-02 19:32 UTC, kt-cpp approved these changes
Ой, принято

2020-07-02 19:32 UTC, merged