vector
sancho20021/first-term pull request #2
Opened 2020-06-28 20:21 UTC by sancho20021

First try

2020-06-29 06:50 UTC, kt-cpp requested changes

2020-06-29 06:50 UTC, kt-cpp commented on vector/vector.h
> +T const *vector<T>::begin() const {
у тебя есть нужные typedef на итераторы, зачем указатели?

2020-06-29 06:50 UTC, kt-cpp commented on vector/vector.h
> +    for (size_t i = 0; i < end - start; i++) {
не верный порядок деструкторов

2020-06-29 06:50 UTC, kt-cpp commented on vector/vector.h
> +    iterator insert(iterator pos, T const &); // O(N) weak
для insert и erase достаточно перегрузок с const_iterator, об этом говорилось на лекции

2020-06-29 06:50 UTC, kt-cpp commented on vector/vector.h
> +    void destroy_elements(const vector::iterator start, const vector::iterator end);
по смыслу ты работаешь с указателем на память, не с итератором (хоть тип и совпадает). + сделать static

2020-06-29 06:50 UTC, kt-cpp commented on vector/vector.h
> +vector<T>::vector() {
vector() : ... {}

2020-06-29 06:50 UTC, kt-cpp commented on vector/vector.h
> +    size_t delt = last - first;
нужен правильный тип для поинтер арифметики. + проверка того, что отрезок не пуст

2020-06-29 06:50 UTC, kt-cpp commented on vector/vector.h
> +        temp.data_ = static_cast<T *>(operator new(new_capacity * sizeof(T)));
здесь и в копи-конструкторе по сути происходит аллокация и копирование. нужен общий метод

2020-06-29 06:50 UTC, kt-cpp commented on vector/vector.h
> +    T copy = element;
копирование нужно делать только если ты решил аллокнуть новый буфер

2020-06-29 06:50 UTC, kt-cpp commented on vector/vector.h
> +    return data_ + size();
нужно определиться, использушь ты только геттеры или только переменные. лучше 2 вариант.

2020-06-29 06:50 UTC, kt-cpp commented on vector/vector.h
> +    data_[size_ - 1].~T();
pop_back()

2020-06-29 06:50 UTC, kt-cpp commented on vector/vector.h
> +T const &vector<T>::operator[](size_t p) const {
operator[](size_t i) ... operator[](size_t p). как почему и зачем разные буквы?

2020-06-30 12:50 UTC, sancho20021 commented on vector/vector.h
> +T const *vector<T>::begin() const {
исправил все такие штуки

2020-06-30 12:50 UTC, sancho20021 commented on vector/vector.h
> +    for (size_t i = 0; i < end - start; i++) {
теперь иду в правильном

2020-06-30 12:50 UTC, sancho20021 commented on vector/vector.h
> +    iterator insert(iterator pos, T const &); // O(N) weak
Оставил лишь одну реализацию вместо двух

2020-06-30 12:50 UTC, sancho20021 commented on vector/vector.h
> +    void destroy_elements(const vector::iterator start, const vector::iterator end);
Ок

2020-06-30 12:50 UTC, sancho20021 commented on vector/vector.h
> +vector<T>::vector() {
Да

2020-06-30 12:51 UTC, sancho20021 commented on vector/vector.h
> +        temp.data_ = static_cast<T *>(operator new(new_capacity * sizeof(T)));
Я сделал 2 метода copy_elements, который копиирует дату одного в дату другого, а также change_buf, который используется, когда нужно расширить собственный буфер

2020-06-30 12:51 UTC, sancho20021 commented on vector/vector.h
> +    T copy = element;
Не поспоришь

2020-06-30 12:52 UTC, sancho20021 commented on vector/vector.h
> +    return data_ + size();
Заменил на переменные

2020-06-30 12:52 UTC, sancho20021 commented on vector/vector.h
> +    data_[size_ - 1].~T();
Да

2020-06-30 12:52 UTC, sancho20021 commented on vector/vector.h
> +T const &vector<T>::operator[](size_t p) const {
На это даже бог не ответит

2020-06-30 14:29 UTC, kt-cpp commented on vector/vector.h
> +#include <assert.h>
[minor] Сишный хедер в плюсовом коде

2020-06-30 14:29 UTC, kt-cpp commented on vector/vector.h
> +#include <iostream>
[minor] Не представляю где в реализации вектора понадобятся объект оттуда

2020-06-30 14:29 UTC, kt-cpp commented on vector/vector.h
> +    typedef T const *const_iterator;
[note] `using` вместо `typedef` смотрится лучше

2020-06-30 14:29 UTC, kt-cpp commented on vector/vector.h
> +    T *my_alloc(size_t size);
[minor] Какие у него причины не быть статическим?

2020-06-30 14:29 UTC, kt-cpp commented on vector/vector.h
> +    iterator insert(iterator pos, T const &); // O(N) weak
* Ты оставил объявление для обеих так что будь добр реализовать обе
* Если оставлять одну, то с менее строгими требованиями, т.к. c `const_iterator`

2020-06-30 14:38 UTC, kt-cpp commented on vector/vector.h
> +    for (size_t i = size - 1; i != -1; i--) {
Сравнение беззнакогово со знаковым. Перепиши нормально

2020-06-30 14:38 UTC, kt-cpp commented on vector/vector.h
> +size_t vector<T>::increase_capacity() {
Зачем эта функция что-то возвращает?

2020-06-30 14:38 UTC, kt-cpp commented on vector/vector.h
> +        temp.data_ = static_cast<T *>(operator new(new_capacity * sizeof(T)));
Всё еще выделяется общий код, как, например, функция которая принимает размер и старые данные и возвращает буффер этого размера с копией нужных данных.
Однако этот недочёт переводится в раздел [minor]

2020-06-30 14:39 UTC, kt-cpp requested changes
Не всё поправил

2020-06-30 16:53 UTC, sancho20021 commented on vector/vector.h
> +size_t vector<T>::increase_capacity() {
Теперь не возвращает!

2020-06-30 16:53 UTC, sancho20021 commented on vector/vector.h
> +    for (size_t i = size - 1; i != -1; i--) {
Прееписал

2020-06-30 16:53 UTC, sancho20021 commented on vector/vector.h
> +    T *my_alloc(size_t size);
Ну да(

2020-06-30 16:53 UTC, sancho20021 commented on vector/vector.h
> +    typedef T const *const_iterator;
Ок

2020-06-30 16:54 UTC, sancho20021 commented on vector/vector.h
> +#include <iostream>
Кажется случайно заимпортилось когда тестил

2020-06-30 16:54 UTC, sancho20021 commented on vector/vector.h
> +#include <assert.h>
ок

2020-06-30 16:55 UTC, sancho20021 commented on vector/vector.h
> +        temp.data_ = static_cast<T *>(operator new(new_capacity * sizeof(T)));
Выделил, теперь copy_elements возвращает новый буфер, а не записывает в поданный. Из-за этого код сократился

2020-06-30 16:55 UTC, sancho20021 commented on vector/vector.h
> +    iterator insert(iterator pos, T const &); // O(N) weak
Остасил одну

2020-06-30 17:41 UTC, kt-cpp approved these changes

2020-06-30 17:41 UTC, merged