Big_Integer done
sancho20021/first-term pull request #3
Opened 2020-07-06 09:52 UTC by sancho20021

2020-07-06 10:27 UTC, kt-cpp requested changes
Обновите тесты

2020-07-06 11:36 UTC, sancho20021 commented
> Обновите тесты

готово

2020-07-06 13:59 UTC, kt-cpp requested changes
Для начала хватит, исправляйте

2020-07-06 13:59 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    digits.push_back(a == INT32_MIN ? 2147483648u : static_cast<uint32_t>(abs(a)));
Эту гениальную константу можно вынести и как-нибудь назвать

2020-07-06 13:59 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        digits(other.digits) {}
Можно = default

2020-07-06 13:59 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    uint32_t base = 1000000000;
Константа не по кодстайлу (заглавные буквы)

2020-07-06 13:59 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    for (; i < len; i += 9) {
Искусственное усложнение инициализации i, сделайте проще

2020-07-06 13:59 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    for (; i < len; i += 9) {
9 вынесите в константы

2020-07-06 13:59 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    x.sign = true;
Зачем так сложно (особенно в конце)?

2020-07-06 13:59 UTC, kt-cpp commented on bigint/big_integer.h
> +
По какой причине вот это всё у вас объявлено и внутри класса, и снаружи?

2020-07-06 13:59 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    return digits.size() == 1 && digits[0] == 0;
Заведите себе константу ZERO = big_integer(0) и сравнивайте с ней

2020-07-06 13:59 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    }
То есть -0 не равно 0? В принципе наличие -0 - это ошибка, избавьтесь от него

2020-07-06 13:59 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    }
== ZERO

2020-07-06 14:23 UTC, sancho20021 commented on bigint/big_integer.cpp
> +    }
Исправил

2020-07-06 14:54 UTC, sancho20021 commented on bigint/big_integer.cpp
> +    for (; i < len; i += 9) {
Да уж, можно было гораздо проще)

2020-07-06 14:54 UTC, sancho20021 commented on bigint/big_integer.cpp
> +    for (; i < len; i += 9) {
Готово

2020-07-06 14:55 UTC, sancho20021 commented on bigint/big_integer.h
> +
Как было, так оставил, но понял, что можно оставить одно из двух (френд)

2020-07-06 14:55 UTC, sancho20021 commented on bigint/big_integer.cpp
> +    return digits.size() == 1 && digits[0] == 0;
Ок!

2020-07-06 14:57 UTC, sancho20021 commented on bigint/big_integer.cpp
> +    uint32_t base = 1000000000;
ОК

2020-07-06 14:58 UTC, sancho20021 commented on bigint/big_integer.cpp
> +        digits(other.digits) {}
Согласен)

2020-07-06 14:58 UTC, sancho20021 commented on bigint/big_integer.cpp
> +    digits.push_back(a == INT32_MIN ? 2147483648u : static_cast<uint32_t>(abs(a)));
Вынес!

2020-07-06 15:29 UTC, sancho20021 commented on bigint/big_integer.cpp
> +    x.sign = true;
По-другому в моей реализации не получается. Нужно именно сложить модуль числа, поэтому знак для начала приходится поменять

2020-07-06 15:30 UTC, sancho20021 commented on bigint/big_integer.cpp
> +    }
Я проверил почти по всем функциям, на выходе и входах никогда не допускаются орицательные нули. В данную функцию 0 вообще не придет, так как он отсечется раньше.

2020-07-06 21:56 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    }
Тернарник

2020-07-06 21:56 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    *this = *this + 1;
Раз уж завели константу ONE, то поиспользуйте здесь

2020-07-06 21:56 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        return res;
ZERO?

2020-07-06 21:56 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    d.sign = false;
В итоге вы написали все возможные abs'ы, кроме классического. Он уберёт лишние пару строк

2020-07-06 21:56 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    for (auto i = static_cast<uint32_t>(a.digits.size()); i > 0; i--) {
Треш, для размеров придумали типа size_t и как им приятно итерироваться
for (size_t i = a.size(); i --> 0;) - от a.size() до 0, например

2020-07-06 21:56 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    } else return (!a.sign && abs_compare(a, b) == -1) || (a.sign && abs_compare(a, b) == 1);
Тут можно хотя бы один тернарник (может даже для else-условия, которое совсем ни на что не похоже)

2020-07-06 21:56 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    } else return (!a.sign && abs_compare(a, b) == 1) || (a.sign && abs_compare(a, b) == -1);
И тут

2020-07-06 22:04 UTC, sancho20021 commented on bigint/big_integer.cpp
> +    }
Готово

2020-07-06 22:06 UTC, sancho20021 commented on bigint/big_integer.cpp
> +    *this = *this + 1;
Поправил

2020-07-06 22:10 UTC, sancho20021 commented on bigint/big_integer.cpp
> +        return res;
Да

2020-07-06 22:20 UTC, sancho20021 commented on bigint/big_integer.cpp
> +    for (auto i = static_cast<uint32_t>(a.digits.size()); i > 0; i--) {
Мда

2020-07-06 22:30 UTC, sancho20021 commented on bigint/big_integer.cpp
> +    } else return (!a.sign && abs_compare(a, b) == -1) || (a.sign && abs_compare(a, b) == 1);
вынес общий код, исправил

2020-07-06 22:30 UTC, sancho20021 commented on bigint/big_integer.cpp
> +    } else return (!a.sign && abs_compare(a, b) == 1) || (a.sign && abs_compare(a, b) == -1);
вынес общий код, исправил

2020-07-06 22:45 UTC, sancho20021 commented on bigint/big_integer.cpp
> +    d.sign = false;
Done!

2020-07-07 08:07 UTC, kt-cpp approved these changes

2020-07-07 08:07 UTC, merged